export const GET_ERROR = "GET_ERROR";
//CATEGORY
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_SPECIFIC_CATEGORY = "GET_SPECIFIC_CATEGORY";
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";

//USER
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_SPECIFIC_USER = "GET_SPECIFIC_USER";

//MANAGER
export const GET_ALL_MANAGERS = "GET_ALL_MANAGERS";
export const GET_SPECIFIC_MANAGER = "GET_SPECIFIC_MANAGER";

//OFFER
export const CREATE_OFFER = "CREATE_OFFER";
export const GET_ALL_OFFERS = "GET_ALL_OFFERS";
export const GET_SEPECIFIC_OFFER = "GET_SEPECIFIC_OFFER";
export const GET_OFFER_LIKE = "GET_OFFER_LIKE";
export const DELETE_OFFER = "DELETE_OFFER";
export const GET_OFFERS_PAGE = "GET_OFFERS_PAGE";
export const EDIT_OFFER = "EDIT_OFFER";

//RESERVATION
export const GET_ALL_RESERVATIONS = "GET_ALL_RESERVATIONS";
